// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pos-redesign/Current.tsx": () => import("../components/mockups/pos-redesign/Current.tsx"),
  "./components/mockups/pos-redesign/VariantBright.tsx": () => import("../components/mockups/pos-redesign/VariantBright.tsx"),
  "./components/mockups/pos-redesign/VariantDark.tsx": () => import("../components/mockups/pos-redesign/VariantDark.tsx"),
  "./components/mockups/icon-library/BoldSolid.tsx": () => import("../components/mockups/icon-library/BoldSolid.tsx"),
  "./components/mockups/icon-library/Duotone.tsx": () => import("../components/mockups/icon-library/Duotone.tsx"),
  "./components/mockups/icon-library/SoftOutline.tsx": () => import("../components/mockups/icon-library/SoftOutline.tsx")
};
