// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/icon-library/BoldSolid.tsx": () => import("../components/mockups/icon-library/BoldSolid.tsx"),
  "./components/mockups/icon-library/Duotone.tsx": () => import("../components/mockups/icon-library/Duotone.tsx"),
  "./components/mockups/icon-library/SoftOutline.tsx": () => import("../components/mockups/icon-library/SoftOutline.tsx")
};
